//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassCartoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPANY_CARTOONS
    {
        public int CC_CR { get; set; }
        public int CC_CP { get; set; }
        public int CC_ID { get; set; }
    
        public virtual CARTOONS CARTOONS { get; set; }
        public virtual DIC_COMPANY DIC_COMPANY { get; set; }
    }
}
