//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassCartoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_CARTOON_STATUSES
    {
        public DIC_CARTOON_STATUSES()
        {
            this.CARTOONS = new HashSet<CARTOONS>();
        }
    
        public int CS_ID { get; set; }
        public string CS_NAME { get; set; }
    
        public virtual ICollection<CARTOONS> CARTOONS { get; set; }
    }
}
