//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassCartoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_DIRACTORS
    {
        public DIC_DIRACTORS()
        {
            this.DIRACTORS_CARTOONS = new HashSet<DIRACTORS_CARTOONS>();
            this.LOGIN = new HashSet<LOGIN>();
        }
    
        public int DR_ID { get; set; }
        public string DR_NAME { get; set; }
        public string DR_INFO { get; set; }
    
        public virtual ICollection<DIRACTORS_CARTOONS> DIRACTORS_CARTOONS { get; set; }
        public virtual ICollection<LOGIN> LOGIN { get; set; }
    }
}
