//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassCartoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_COUNRTY
    {
        public DIC_COUNRTY()
        {
            this.DIC_COMPANY = new HashSet<DIC_COMPANY>();
        }
    
        public int CT_ID { get; set; }
        public string CT_NAME { get; set; }
        public string CT_INFO { get; set; }
    
        public virtual ICollection<DIC_COMPANY> DIC_COMPANY { get; set; }
    }
}
