//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassCartoons
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string LG_LOGIN { get; set; }
        public string LG_PASSWORD { get; set; }
        public Nullable<int> LG_ISADMIN { get; set; }
        public Nullable<int> LG_DR { get; set; }
    
        public virtual DIC_DIRACTORS DIC_DIRACTORS { get; set; }
    }
}
